language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - allowed_dupes=CONTRIBUTING,github.com,home-assistant.io
  - awesome_bot README.md --white-list $allowed_dupes
  - danger
notifications:
  email: false
